Update error messages in eslint-ratchet

diff --git a/bin/eslint-ratchet b/bin/eslint-ratchet
--- a/bin/eslint-ratchet
+++ b/bin/eslint-ratchet
@@ -15,18 +15,18 @@ NOW=$(./node_modules/.bin/eslint --format unix . | tail -n 1 | awk '{ print $1 }
 # If there are more errors now than there used to be, fail
 if (( NOW > PREV )); then
   DELTA=$(( NOW - PREV))
-  echo "ERROR: ESLint errors have increased by ${DELTA}" >&2
+  echo "eslint-ratchet error: eslint errors have increased by ${DELTA}" >&2
   exit 1
 elif (( NOW < PREV )); then
   if [ "$ARG" == "ci" ]; then
-    echo "ERROR: Expected ${PREV} errors but found ${NOW}.  Run './bin/eslint-ratchet' and commit .eslint-ratchet-high-water-mark file" >&2
+    echo "eslint-ratchet error: Expected ${PREV} errors but found ${NOW}.  Run './bin/eslint-ratchet' and commit .eslint-ratchet-high-water-mark file" >&2
     exit 2
   else
     echo "WIN: ESLint errors have decreased from ${PREV} to ${NOW}.  Ratcheting down ..."
+    echo "Make sure to commit .eslint-ratchet-high-water-mark"
     echo "$NOW" > .eslint-ratchet-high-water-mark
     exit 0
   fi
 else
-  echo "No change in number of ESLint errors"
   exit 0
 fi
